# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- master
- pu

jobs:
- job: linux
  displayName: Linux
  condition: succeeded()
  pool:
    vmImage: 'ubuntu-latest'

  variables:
    GOBIN:  '$(GOPATH)/bin' # Go binaries path
    GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
    modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code

  steps:
  - script: |
      mkdir -p '$(GOBIN)'
      mkdir -p '$(GOPATH)/pkg'
      mkdir -p '$(modulePath)'
      shopt -s extglob
      shopt -s dotglob
      mv !(gopath) '$(modulePath)'
      echo '##vso[task.prependpath]$(GOBIN)'
      echo '##vso[task.prependpath]$(GOROOT)/bin'
    displayName: 'Set up the Go workspace'

  - script: |
      export GO111MODULE=on
      go version
      make
    workingDirectory: '$(modulePath)'
    displayName: 'Get dependencies, then build'

  - script: |
      make ut
    workingDirectory: '$(modulePath)'
    displayName: 'Unit test'

  - script: |
      make it
    workingDirectory: '$(modulePath)'
    displayName: 'Integration test'

  - script: |
      export GO111MODULE=on
      go get -u golang.org/x/lint/golint
      make golint
    workingDirectory: '$(modulePath)'
    displayName: 'Code style test'

- job: osx
  displayName: MacOSX
  condition: succeeded()
  pool: Hosted macOS

  variables:
    GOBIN:  '$(GOPATH)/bin' # Go binaries path
    GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
    modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code

  steps:
  - script: |
      mkdir -p '$(GOBIN)'
      mkdir -p '$(GOPATH)/pkg'
      mkdir -p '$(modulePath)'
      shopt -s extglob
      shopt -s dotglob
      mv !(gopath) '$(modulePath)'
      echo '##vso[task.prependpath]$(GOBIN)'
      echo '##vso[task.prependpath]$(GOROOT)/bin'
    displayName: 'Set up the Go workspace'

  - script: |
      export GO111MODULE=on
      go version
      make
    workingDirectory: '$(modulePath)'
    displayName: 'Get dependencies, then build'

  - script: |
      make ut
    workingDirectory: '$(modulePath)'
    displayName: 'Unit test'

  - script: |
      make it
    workingDirectory: '$(modulePath)'
    displayName: 'Integration test'

  - script: |
      export GO111MODULE=on
      go get -u golang.org/x/lint/golint
      make golint
    workingDirectory: '$(modulePath)'
    displayName: 'Code style test'

- job: windows
  displayName: Windows
  condition: succeeded()
  pool:
    vmImage: 'windows-2019'

  variables:
    GOBIN:  '$(GOPATH)/bin' # Go binaries path
    GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
    modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code

  steps:
  - task: PowerShell@2
    displayName: Test in pester
    name: pester
    inputs:
      filePath: 'Invoke-Pester.ps1'
      pwsh: true

  - task: PublishTestResults@2
    displayName: Summery result for pester
    name: summery
    inputs:
      testResultsFormat: 'NUnit'
      testResultsFiles: 'test.pwsh/TEST-*.xml'
      failTaskOnFailedTests: true
